Introduce JSON response in controller
renuo/moirai pull request #46
Opened 2024-11-05 05:40 UTC by CuddlyBunion341

The issue this PR promises to resolve:

https://github.com/user-attachments/assets/e58c00ed-6f39-4230-909d-967df6ab86a5

2024-11-05 09:54 UTC, coorasse requested changes
I don't think we need to support json for all the controller actions. Also this makes it difficult to judge to the change that you actually wanted to do. Can you maybe isolate the change in its own PR?

2024-11-05 09:54 UTC, coorasse commented on app/controllers/moirai/translation_files_controller.rb
I don't think we should support json format if it's not used. It's code that we don't need. For the actions where we only use HTML, there's no need to support json format.

2024-11-13 16:30 UTC, CuddlyBunion341 commented on app/controllers/moirai/translation_files_controller.rb
> +    def get_fallback_translation
Duplicate code 😓

2024-11-13 17:04 UTC, CuddlyBunion341 commented on app/controllers/moirai/translation_files_controller.rb
> +      end
No need for respond_to if the format is already being checked.
```suggestion
      if translation_params[:value].blank? && request.format.json?
        return render json: {fallback_translation: get_fallback_translation}
      end
```

2024-11-13 17:08 UTC, CuddlyBunion341 commented on test/controllers/moirai/translation_files_controller_test.rb
> +  test "update translation with blank value json" do
```suggestion
  test "update translation with blank value JSON" do
```

2024-11-21 21:19 UTC, coorasse approved these changes
Nice! I updated one line and merged!

2024-11-21 21:20 UTC, merged